### ISSUE TITLE
Use diesel migrations

### ISSUE THREAD

**Issue by azhur** [meteroid-oss/meteroid#274]
We are using `refinery` for database migrations. As we recently migrated to diesel it would be nice to use diesel migrations as well. It will allow us to get rid of `deadpool_postgres::Pool`, `deadpool_postgres::Client` (currently used for refinery migrations and in PostgresLock).

**Comment by gaspb** [comment]
clonsed by https://github.com/meteroid-oss/meteroid/pull/316
