### ISSUE TITLE
[BE] Credit note

### ISSUE THREAD

**Issue by gaspb** [meteroid-oss/meteroid#85]
Credit note are used to refund or credit back a customer.
They are linked to an invoice, and can apply to specific product items, and all/some of the amount.
They can be generated automatically (ex: downgrade before the end of the period) or issued via the UI/API.

They can either : 
- emit a refund (auto via stripe, or manual via webhook) (finalized invoice with succeeded payment only) => tracked via `refund_status`
- create a credit grant in meteroid

For each line item, a credit amount is provided, max the amount excl tax

For this issue, use a placeholder for the credit grant part

**Comment by amosehiguese** [comment]
Hi! 
I'm interested in contributing to this project and would like to request to be assigned to this issue if it's available. Could you please guide me on how to proceed?

**Comment by gaspb** [comment]
Hey Amos, we're working on some core db-related refacto and so the repository is a bit too unstable to allow for external contributions at this point. We're working on it ! 
Feel free to join [our discord](https://go.meteroid.com/discord), we'll communicate there when we're ready to open the contributions & create tasks for the community, hopefully within the next couple weeks. 
Thanks !

**Comment by amosehiguese** [comment]
Thanks for the clarity. 
I will be joining the discord then.
